### ISSUE TITLE
Folder Structure and naming Convention adjustments

### ISSUE THREAD

**Issue by mitchell-accipio** [SN-RECIT-formation-a-distance/moodle-tool_htmlbootstrapeditor#6]
This repo is not constructed in a way that makes cloning into Moodle convenient; the contents of `src/` should be the top level of the repo to enable an admin to clone the repo to disk or feed it into a CI/CD pipeline without battling with the subdirectory. I can see that the top level of the repo contains what appear to be install and sync scripts that specifically target your environment - With this listed in the Moodle Plugins Dir, the repo should be environment agnostic. 

> Also, the name `moodle-tool_htmlbootstrapeditor` can break build systems; the convention should have it named simply `tool_htmlbootstrapeditor` 

EDIT: The above about repo naming is completely innaccurate and written whilst busy which is why you should always check your work before you post it

Please can we adjust the folder structure of the repo?

**Comment by jrojas-garrido** [comment]
I'm testing the plugin and I found the same problem, I can't clone directly with git because of the scr/ folder.

**Comment by gustavobazzo** [comment]
Hello @mitchell-accipio and @jrojas-garrido,

Thank you for your proposal. 

When we published this plugin on Moodle.org, this folder structure was reported as a possible issue but not a blocker. That is why our team decided to continue like this at that time. 

For now, we will continue like this due to our dev environment.
